//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFPPE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libretamochalum
    {
        public long idLibMA { get; set; }
        public long idAlumno { get; set; }
        public string NombreLib { get; set; }
        public string Tema { get; set; }
        public bool Documento { get; set; }
        public string Descripcion { get; set; }
    
        public virtual alumnos alumnos { get; set; }
    }
}
