//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFPPE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class plataformaEntities : DbContext
    {
        public plataformaEntities()
            : base("name=plataformaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividades> actividades { get; set; }
        public virtual DbSet<administrador> administrador { get; set; }
        public virtual DbSet<alumnos> alumnos { get; set; }
        public virtual DbSet<archivodocalum> archivodocalum { get; set; }
        public virtual DbSet<archivodocmaestro> archivodocmaestro { get; set; }
        public virtual DbSet<archivoprealum> archivoprealum { get; set; }
        public virtual DbSet<archivopremaes> archivopremaes { get; set; }
        public virtual DbSet<archivospizarronma> archivospizarronma { get; set; }
        public virtual DbSet<calificacion> calificacion { get; set; }
        public virtual DbSet<detallepizarron> detallepizarron { get; set; }
        public virtual DbSet<examen> examen { get; set; }
        public virtual DbSet<generacionpreguntas> generacionpreguntas { get; set; }
        public virtual DbSet<graficacion> graficacion { get; set; }
        public virtual DbSet<inscripcion> inscripcion { get; set; }
        public virtual DbSet<libretamochalum> libretamochalum { get; set; }
        public virtual DbSet<libretamochmaes> libretamochmaes { get; set; }
        public virtual DbSet<maestros> maestros { get; set; }
        public virtual DbSet<materia> materia { get; set; }
        public virtual DbSet<padretutor> padretutor { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<seccion> seccion { get; set; }
        public virtual DbSet<seleccion> seleccion { get; set; }
        public virtual DbSet<tareas> tareas { get; set; }
        public virtual DbSet<tipomateria> tipomateria { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
